### PR TITLE
feat(style): add support for an alternative font

### PR DESCRIPTION
**Pull request by gabaldon**

### CODE REVIEW

**Comment by Tommytrg** [comment]
The following elements will use Avenir

image_2021-04-15_18-12-23
image_2021-04-15_18-15-25
image_2021-04-15_18-17-28

**Comment by aesedepece** [comment]
@gabaldon @Tommytrg Hey hey hey we don't have permission for pushing TTF files for the Avenir font!

**Review by aesedepece — CHANGES_REQUESTED** [review]
Licensing issues

**Comment by aesedepece** [comment]
@gabaldon make sure you delete the commit 842e4ba so the Avenir files are no longer on GitHub :wink:

**Pull request merged**
